# Generated by Django 4.2.7 on 2023-12-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_entry', '0001_initial'),
    ]

    operations = [
                migrations.RunSQL('CREATE TABLE test_book (title TEXT, author TEXT, content TEXT, token_len INT,  vector_info vector(384));')
    ]
