# Generated by Django 4.1.1 on 2023-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
