# Generated by Django 4.2.2 on 2023-06-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_remove_file_uploaded_at_alter_file_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='static/pdfs/'),
        ),
    ]
